In [1]:
import numpy as np
print("Libraries Imported")

Libraries Imported


In [2]:
X = [[0,0,0],
     [0,0,1],
     [0,1,0],
     [0,1,1],
     [1,0,0],
     [1,0,1],
     [1,1,0],
     [1,1,1]]
y_actual = [[0],[1],[0],[0],[1],[1],[0],[1]]
X = np.array(X)
y_actual = np.array(y_actual)

In [3]:
X.shape, y_actual.shape

((8, 3), (8, 1))

In [4]:
def sigmoid(X):
    return 1/(1+np.exp(-X)) #sigmoid activation function

In [5]:
W = np.random.randn(3,1)
err_list = []
for i in range(20):
    y_predict = sigmoid(np.dot(X,W))
    error = y_predict - y_actual
    dw = np.dot(X.T,error)
    W = W-dw
    err_list.append(np.sum(np.square(error)))

In [6]:
W #parameters for the neuron

array([[ 3.48769331],
       [-5.37029   ],
       [ 3.48489491]])

In [7]:
y_predict

array([[0.5       ],
       [0.96818793],
       [0.00514137],
       [0.13590793],
       [0.96828897],
       [0.99892509],
       [0.13629426],
       [0.82766446]])

In [8]:
np.round(y_predict) #rounded values of y_predict

array([[0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.]])

In [9]:
err_list #error concurred after every loop

[3.1857949521591005,
 1.5509206138929799,
 0.9432813234861319,
 0.6948554471945342,
 0.5887654211825977,
 0.5224384962971651,
 0.4799052984592046,
 0.44856423905626625,
 0.42442999905334633,
 0.4051927747583407,
 0.38947105148768,
 0.37637201346069105,
 0.3652861172069737,
 0.35578231756904416,
 0.3475461831829689,
 0.34034245273736985,
 0.33399128321656085,
 0.32835264837619804,
 0.3233157771992978,
 0.3187918160661437]

End of code.